language: ruby
rvm:
  - 1.8.7
before_script:
after_script:
script:
branches:
  only:
    - master
env:
  - PUPPET_VERSION=3.1.0
  - PUPPET_VERSION=2.7.19
notifications:
  email: false
gemfile: Gemfile
